### ISSUE TITLE
[TODO]

### ISSUE THREAD

**Issue by allie0147** [allie0147/RxSwift_UITableView#1]
2021.08.19
---
- [ ]  8a8cf100f89fc1b1f49e35a42e46f60992330564 make CommentVC 
- [ ]  8a8cf100f89fc1b1f49e35a42e46f60992330564 make CommentVM 
- [ ]  8a8cf100f89fc1b1f49e35a42e46f60992330564 append API to CommentVM
